export enum UserRole {
  ADMIN = 'ADMIN',
  BERTH_PLANNER = 'BERTH_PLANNER',
  YARD_PLANNER = 'YARD_PLANNER',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  CLIENT = 'CLIENT',
  DOCUMENTATION_SERVICE = 'DOCUMENTATION_SERVICE'
} 